### PR TITLE
Remove vendor from cache. May fix Travis auth.

### PR DESCRIPTION
**Pull request by soullivaneuh**
ping @greg0ire.

### CODE REVIEW

**Comment by greg0ire** [comment]
Fingers crossing in progress…

**Comment by soullivaneuh** [comment]
;-)

**Comment by greg0ire** [comment]
No token in sight. Looks good :)

**Comment by greg0ire** [comment]
see https://github.com/composer/composer/issues/4147#issuecomment-115258930

**Comment by greg0ire** [comment]
Errr… why was the job cancelled ?

**Comment by soullivaneuh** [comment]
https://travis-ci.org/sonata-project/SonataAdminSearchBundle/jobs/68323405#L157

:ok_hand:

**Comment by soullivaneuh** [comment]
Which one? See nothing about that: https://travis-ci.org/sonata-project/SonataAdminSearchBundle/builds/68323378

**Comment by greg0ire** [comment]
Oh I'm tired I think… too many tabs open

**Comment by soullivaneuh** [comment]
Tests passed! Champagne! ;-)

**Comment by greg0ire** [comment]
\o/

**Pull request merged**
