### PR TITLE
DevKit updates for 1.x branch

### PR DESCRIPTION
**Pull request by SonataCI**

### CODE REVIEW

**Comment by OskarStark** [comment]
Looks like we have some versioning problem with ruflin elastica

**Comment by greg0ire** [comment]
Indeed, see https://github.com/ruflin/Elastica/issues/1559

**Comment by greg0ire** [comment]
Several solutions:
1. wait for a fix
2. blacklist 2.3.1
3. drop php 5

**Comment by OskarStark** [comment]
+1 for 3

**Review by greg0ire — APPROVED** [review]

**Pull request merged**
