### PR TITLE
Travis: Cleanup configuration

### PR DESCRIPTION
**Pull request by core23**
- cleanup old symfony 2.8 and 3.0 hacks
- moved **php-cs-fixer** to travis
- **php-cs-fixers** runs once under PHP7
- **sphinx-build** runs once under PHP7
- added PHP nightly builds

Refs https://github.com/sonata-project/SonataAdminBundle/pull/3584

### CODE REVIEW

**Comment by core23** [comment]
@greg0ire Can you have a look at the docs build?

**Comment by greg0ire** [comment]
Made a PR on your PR ;)

**Comment by greg0ire** [comment]
For the php 7 build : `BoolQuery` can be used instead of `Bool`

**Comment by greg0ire** [comment]
Made another PR for this :)

**Comment by greg0ire** [comment]
I'll try to make it BC

**Comment by greg0ire** [comment]
Or not. This bundle is it's its early stages, let's just drop support for early versions of elastica.

**Comment by greg0ire** [comment]
@core23 : made yet another PR!

**Comment by core23** [comment]
:+1: great work @greg0ire

**Comment by greg0ire** [comment]
Thanks @core23 ! And thank git for its distributed model!

**Comment by core23** [comment]
You have merge permission here @greg0ire oO

**Comment by greg0ire** [comment]
Yes it's the only bundle where I have it. It was started by me and my former boss, that's why ;)

**Pull request merged**
