### PR TITLE
Very basic sort implementation

### PR DESCRIPTION
**Pull request by magedan**
This will allow to use standard Sonata Datagrid's sorting feature.

### CODE REVIEW

**Comment by greg0ire** [comment]
Thank you for your contribution

> This will allow to use standard Sonata Datagrid's sorting feature.

This would look great in the commit message. Could you please reword your commit like this : 

> implement datagrid sort
> 
> This implementation is very basic, because…

**Comment by rande** [comment]
Can you add unit test ? thanks

**Comment by magedan** [comment]
Sure, will do.
Thank you for the quick review.

**Comment by magedan** [comment]
I've added ProxyQuery tests, but PHPUnit gives me following error:

1) Sonata\AdminSearchBundle\Tests\DependencyInjection\Compiler\DatagridBuilderInjectionCompilerPassTest::testDatagridBuilderIsInjected
Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: The service definition "sonata.admin.search.datagrid_builder" does not exist.

I'm not sure why that happened..

**Comment by magedan** [comment]
Btw, there is a `__clone` method which has {@inheritdoc} declaration, but interface has not declared it:

``` php
    /**
     * {@inheritdoc}
     */
    public function __clone()
    {
        $this->query = clone $this->queryBuilder;
    }
```

Also, it refers to the non-existent `$this->queryBuilder` property. Any suggestions?

**Comment by magedan** [comment]
I'm sorry, closed the PR accidentally

**Comment by greg0ire** [comment]
> I've added ProxyQuery tests, but PHPUnit gives me following error:
> 
> 1) Sonata\AdminSearchBundle\Tests\DependencyInjection\Compiler\DatagridBuilderInjectionCompilerPassTest::testDatagridBuilderIsInjected
> Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: The service definition "sonata.admin.search.datagrid_builder" does not exist.
> 
> I'm not sure why that happened..

Looks like I started writing a test, and never finished it. This is fixed in master now, you can rebase. Thank you for catching this!

And thank you for rewriting the commit message, it is much better!

**Comment by greg0ire** [comment]
Regarding the `__clone` method, this class was copy/pasted/adapted from [this one](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Datagrid/ProxyQuery.php), so your "inheritdoc" comment applies to this bundle too, I guess. Since we do not have this property, I simply removed the `__clone` method in master for the time being.

**Comment by greg0ire** [comment]
Travis is setup, could you please rebase your branch on the latest master so that your changes can be tested ? I see this is your very first PR, don't hesitate to ask for more details if you need.

**Comment by greg0ire** [comment]
Two problems with your PR : 
1. there should be no merge commit
2. there should be only one commit

Fixing 2. is pretty easy : `git rebase origin/master`

Fixing 1. is a bit more complicate : you should do an interactive rebase : `git rebase -i origin/master` , and squash all the commits together. I'm going to do it for you this time, but try to learn how to do it ;) I think there are some exercices that deal with that in [this tutorial](http://pcottle.github.io/learnGitBranching/)

**Comment by greg0ire** [comment]
I'm closing without merging because I did it manually (look at the last commit, it is yours). Thanks a lot for the contribution!

**Comment by greg0ire** [comment]
P.S. : if you want to appear as a contributor of any project, you need to configure your git (and probably github) email (but maybe you value your privacy :wink: ), because this is how github identifies people

**Comment by magedan** [comment]
Oh, well, I know how to squash commits, but didn't know it is required. Thanks for pointing this out, will be more attentive in future.
I'm glad I can help you with this great project!

**Comment by greg0ire** [comment]
It is not really a requirement, but 2 of your commits had the same commit message, and the first one had the commit message I asked you to change (have a look at the commit tab of this PR). The fourth one was a merge commit.

**Pull request closed without merging**
