### PR TITLE
Fix wrong query term escaping in StringFilter

### LINKED ISSUE #5: Escaped terms in filter field raises exception
Input of special characters/terms (like + - && || ! etc) as a string filter value causes following error:

> The produced query is not a valid json string : "{"match":{"name":{"query":"test-hyphen","operator":"and"}}}"
> 500 Internal Server Error - InvalidException

This is because of the \Elastica\Util::escapeTerm() call in Sonata\AdminSearchBundle\Filter\StringFilter:

``` php
        $queryBuilder
            ->fieldOpen($secondOperator)
                ->fieldOpen($field)
                    ->field('query', Util::escapeTerm($data['value']))
                    ->field('operator', 'and')
                ->fieldClose()
            ->fieldClose();
```

If I remove Util::escapeTerm() call Elastica works as expected, here is the full query:

``` javascript
{"query":{"bool":{"must":[{"match":{"name":{"query":"test-hyphen","operator":"and"}}}]}},"sort":{"id":{"order":"desc"}},"from":0,"size":32}
```

Is this really necessary to apply escapeTerm here?

### PR DESCRIPTION
**Pull request by magedan**
After a thorough investigation I realized that only two characters must be escaped: " and \

This PR should fix #5.

### CODE REVIEW

**Comment by greg0ire** [comment]
Ok, let me check that this does not reopen #1

**Comment by greg0ire** [comment]
Looks like it does not :) .

**Comment by greg0ire** [comment]
I'm closing because I merged your PR manually. Thanks!

**Comment by greg0ire** [comment]
Again, if you wish to have this contributions to open-source recognized by github, you need to add the email you used to do these commits to your profile.

**Comment by magedan** [comment]
Thanks for the suggestion, but I don't really need to be appeared in the contributors list.

Still, happy to help you! My current project heavily depends on your work.

**Comment by greg0ire** [comment]
Well that's great to hear! I don't know es that much myself, but rest assured that I will always look at your contributions quickly and merge them in a reasonable time frame.

**Pull request closed without merging**
